import { createCRUD } from "../api/crudFactory.js";

export const ENTITY_CONFIG = {
  products: {
    endpoint: "/products",
    api: createCRUD("/products"),
    title: "Products",
    fields: [
      {
        name: "category",
        label: "Category",
        type: "select",
        required: true,
        optionsSource: "categories",
        group: "Classification",
      },
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        group: "Classification",
      },
      {
        name: "slug",
        label: "Slug",
        type: "text",
        required: true,
        group: "Classification",
      },
      {
        name: "collectionName",
        label: "Collection Name",
        type: "text",
        group: "Classification",
      },
      {
        name: "categoryLabel",
        label: "Category Label",
        type: "text",
        group: "Classification",
      },
      {
        name: "series",
        label: "Series",
        type: "text",
        group: "Classification",
      },
      {
        name: "family",
        label: "Family",
        type: "text",
        group: "Classification",
      },
      { name: "finish", label: "Finish", type: "text", group: "Surface" },
      { name: "thickness", label: "Thickness", type: "text", group: "Surface" },
      { name: "material", label: "Material", type: "text", group: "Surface" },
      { name: "price", label: "Price", type: "number", group: "Surface" },
      {
        name: "sizes",
        label: "Sizes (comma separated)",
        type: "text",
        isArray: true,
        group: "Variants",
      },
      {
        name: "colors",
        label: "Colors (comma separated)",
        type: "text",
        isArray: true,
        group: "Variants",
      },
      {
        name: "applications",
        label: "Applications (comma separated)",
        type: "text",
        isArray: true,
        group: "Variants",
      },
      {
        name: "tags",
        label: "Tags (comma separated)",
        type: "text",
        isArray: true,
        group: "Variants",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        group: "Details",
      },
      {
        name: "featured",
        label: "Featured",
        type: "checkbox",
        group: "Details",
      },
      {
        name: "isNewItem",
        label: "Is New Item",
        type: "checkbox",
        group: "Details",
      },
      { name: "image", label: "Primary Image", type: "file", group: "Media" },
      {
        name: "image2",
        label: "Secondary Image",
        type: "file",
        group: "Media",
      },
      {
        name: "gallery",
        label: "Gallery Images",
        type: "file",
        multiple: true,
        group: "Media",
      },
    ],
    columns: ["name", "slug", "category", "featured", "isNewItem"],
  },
  categories: {
    endpoint: "/categories",
    api: createCRUD("/categories"),
    title: "Categories",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "tagline", label: "Tagline", type: "text" },
      { name: "application", label: "Application", type: "text" },
      { name: "count", label: "Product Count", type: "number" },
      { name: "image", label: "Image", type: "file" },
    ],
    columns: ["name", "slug", "count"],
  },
  collections: {
    endpoint: "/collections",
    api: createCRUD("/collections"),
    title: "Collections",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "text", required: true },
      { name: "tagline", label: "Tagline", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "year", label: "Year", type: "number" },
      { name: "productCount", label: "Product Count", type: "number" },
      { name: "featured", label: "Featured", type: "checkbox" },
      { name: "image", label: "Image", type: "file" },
    ],
    columns: ["name", "slug", "year", "featured"],
  },
  testimonials: {
    endpoint: "/testimonials",
    api: createCRUD("/testimonials"),
    title: "Testimonials",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "text" },
      { name: "company", label: "Company", type: "text" },
      { name: "project", label: "Project", type: "text" },
      { name: "quote", label: "Quote", type: "textarea", required: true },
      { name: "rating", label: "Rating (1-5)", type: "number" },
      { name: "avatar", label: "Avatar", type: "file" },
    ],
    columns: ["name", "company", "rating"],
  },
  inspirations: {
    endpoint: "/inspirations",
    api: createCRUD("/inspirations"),
    title: "Inspirations",
    fields: [
      {
        name: "roomKey",
        label: "Room",
        type: "select",
        required: true,
        options: [
          { label: "All Rooms", value: "all" },
          { label: "Living Room", value: "livingRoom" },
          { label: "Bathroom", value: "bathroom" },
          { label: "Kitchen", value: "kitchen" },
          { label: "Bedroom", value: "bedroom" },
          { label: "Outdoor", value: "outdoor" },
        ],
        group: "Content",
      },
      { name: "title", label: "Title", type: "text", group: "Content" },
      {
        name: "collectionName",
        label: "Collection Name",
        type: "text",
        group: "Content",
      },
      { name: "image", label: "Image", type: "file", group: "Media" },
    ],
    columns: ["title", "roomKey", "collectionName"],
  },
  promoOffers: {
    endpoint: "/promo-offers",
    api: createCRUD("/promo-offers"),
    title: "Promo Offers",
    fields: [
      { name: "badge", label: "Badge", type: "text", group: "Content" },
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        group: "Content",
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        group: "Content",
      },
      { name: "ctaLabel", label: "CTA Label", type: "text", group: "Content" },
      { name: "ctaLink", label: "CTA Link", type: "text", group: "Content" },
      {
        name: "backgroundImage",
        label: "Background Image",
        type: "file",
        group: "Design",
      },
      {
        name: "backgroundColor",
        label: "Background Color",
        type: "text",
        group: "Design",
      },
      { name: "textColor", label: "Text Color", type: "text", group: "Design" },
      {
        name: "accentColor",
        label: "Accent Color",
        type: "text",
        group: "Design",
      },
      {
        name: "sortOrder",
        label: "Sort Order",
        type: "number",
        group: "Settings",
      },
      {
        name: "isActive",
        label: "Active",
        type: "checkbox",
        group: "Settings",
      },
    ],
    columns: ["title", "badge", "sortOrder", "isActive"],
  },
  stats: {
    endpoint: "/stats",
    api: createCRUD("/stats"),
    title: "Stats",
    fields: [
      { name: "label", label: "Label", type: "text", required: true },
      { name: "value", label: "Value", type: "text", required: true },
    ],
    columns: ["label", "value"],
  },
  catalogues: {
    endpoint: "/catalogues",
    api: createCRUD("/catalogues"),
    title: "Catalogues",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "subtitle", label: "Subtitle", type: "text" },
      { name: "type", label: "Type", type: "text" },
      { name: "size", label: "Size", type: "text" },
      { name: "pages", label: "Pages", type: "number" },
      { name: "year", label: "Year", type: "number" },
      { name: "cover", label: "Cover Image", type: "file" },
    ],
    columns: ["title", "type", "year"],
  },
  // finishTypes: {
  //   endpoint: "/finish-types",
  //   api: createCRUD("/finish-types"),
  //   title: "Finish Types",
  //   fields: [{ name: "name", label: "Name", type: "text", required: true }],
  //   columns: ["name"],
  // },
  // tileSizes: {
  //   endpoint: "/tile-sizes",
  //   api: createCRUD("/tile-sizes"),
  //   title: "Tile Sizes",
  //   fields: [
  //     {
  //       name: "productSlug",
  //       label: "Product",
  //       type: "select",
  //       required: true,
  //       optionsSource: "products",
  //       group: "Product Mapping",
  //     },
  //     {
  //       name: "productName",
  //       label: "Product Name",
  //       type: "text",
  //       group: "Product Mapping",
  //     },
  //     {
  //       name: "category",
  //       label: "Category",
  //       type: "select",
  //       required: true,
  //       optionsSource: "categories",
  //       group: "Product Mapping",
  //     },
  //     {
  //       name: "size",
  //       label: "Tile Size (e.g. 600x1200)",
  //       type: "text",
  //       required: true,
  //       group: "Tile Spec",
  //     },
  //     {
  //       name: "color",
  //       label: "Tile Color",
  //       type: "text",
  //       required: true,
  //       group: "Tile Spec",
  //     },
  //     { name: "finish", label: "Finish", type: "text", group: "Tile Spec" },
  //     {
  //       name: "thickness",
  //       label: "Thickness",
  //       type: "text",
  //       group: "Tile Spec",
  //     },
  //     {
  //       name: "value",
  //       label: "Legacy Value (optional)",
  //       type: "text",
  //       group: "Tile Spec",
  //     },
  //   ],
  //   columns: ["productSlug", "category", "size", "color", "finish"],
  // },
  spaces: {
    endpoint: "/spaces",
    api: createCRUD("/spaces"),
    title: "Spaces",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "image", label: "Image", type: "file" },
    ],
    columns: ["name"],
  },
  pageHeroImages: {
    endpoint: "/page-hero-images",
    api: createCRUD("/page-hero-images"),
    title: "Page Hero Images",
    fields: [
      { name: "page", label: "Page Name", type: "text", required: true },
      { name: "image", label: "Image", type: "file" },
    ],
    columns: ["page"],
  },
  heroSlides: {
    endpoint: "/hero-slides",
    api: createCRUD("/hero-slides"),
    title: "Hero Slides",
    fields: [
      { name: "ctaLink", label: "CTA Link", type: "text" },
      { name: "image", label: "Image", type: "file" },
    ],
    columns: ["ctaLink"],
  },
  homeApplicationAreas: {
    endpoint: "/home-application-areas",
    api: createCRUD("/home-application-areas"),
    title: "Home App Areas",
    fields: [
      { name: "key", label: "Key", type: "text", required: true },
      { name: "nameKey", label: "Name Key", type: "text", required: true },
      { name: "image", label: "Image", type: "file" },
    ],
    columns: ["key", "nameKey"],
  },
  pressReleases: {
    endpoint: "/press-releases",
    api: createCRUD("/press-releases"),
    title: "Press Releases",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "date", label: "Date", type: "text" },
      { name: "excerpt", label: "Excerpt", type: "textarea" },
      { name: "image", label: "Image", type: "file" },
    ],
    columns: ["title", "category", "date"],
  },
  mediaAssets: {
    endpoint: "/media-assets",
    api: createCRUD("/media-assets"),
    title: "Media Assets",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "type", label: "Type", type: "text" },
      { name: "size", label: "Size", type: "text" },
      { name: "file", label: "File", type: "file" },
    ],
    columns: ["title", "type", "size"],
  },
  coverages: {
    endpoint: "/coverages",
    api: createCRUD("/coverages"),
    title: "Coverages",
    fields: [
      { name: "outlet", label: "Outlet", type: "text", required: true },
      { name: "headline", label: "Headline", type: "text", required: true },
      { name: "year", label: "Year", type: "number" },
    ],
    columns: ["outlet", "headline", "year"],
  },
  contactOfficeLocations: {
    endpoint: "/contact-office-locations",
    api: createCRUD("/contact-office-locations"),
    title: "Office Locations",
    fields: [
      { name: "city", label: "City", type: "text", required: true },
      { name: "address", label: "Address", type: "textarea" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "email", label: "Email", type: "text" },
    ],
    columns: ["city", "phone", "email"],
  },
  tileCalculatorConfigs: {
    endpoint: "/tile-calculator-configs",
    api: createCRUD("/tile-calculator-configs"),
    title: "Calculator Configs",
    fields: [
      {
        name: "defaultBoxCoverage",
        label: "Default Box Coverage",
        type: "number",
      },
      {
        name: "roomPresetDimensions",
        label: "Room Preset Dimensions (comma separated json)",
        type: "text",
        isArray: true,
      },
      {
        name: "wastageOptionValues",
        label: "Wastage Option Values (comma separated)",
        type: "text",
        isArray: true,
      },
      {
        name: "tileFormats",
        label: "Tile Formats (comma separated json)",
        type: "text",
        isArray: true,
      },
    ],
    columns: ["defaultBoxCoverage"],
  },
  siteConfigs: {
    endpoint: "/site-configs",
    api: createCRUD("/site-configs"),
    title: "Site Configurations",
    fields: [
      { name: "logo", label: "Main Logo", type: "file", group: "Branding" },
      { name: "footerLogo", label: "Footer Logo", type: "file", group: "Branding" },
      { name: "siteName", label: "Site Name", type: "text", group: "Branding" },
      { name: "siteTagline", label: "Site Tagline", type: "text", group: "Branding" },
      { name: "footerDescription", label: "Footer Description", type: "textarea", group: "Branding" },

      { name: "contactEmail", label: "Contact Email", type: "text", group: "Contact Info" },
      { name: "contactPhones", label: "Contact Phones (comma separated)", type: "text", isArray: true, group: "Contact Info" },
      { name: "address", label: "Office Address", type: "textarea", group: "Contact Info" },

      { name: "socialLinks.instagram", label: "Instagram URL", type: "text", group: "Social Media" },
      { name: "socialLinks.facebook", label: "Facebook URL", type: "text", group: "Social Media" },
      { name: "socialLinks.twitter", label: "Twitter URL", type: "text", group: "Social Media" },
      { name: "socialLinks.linkedin", label: "LinkedIn URL", type: "text", group: "Social Media" },
      { name: "socialLinks.youtube", label: "YouTube URL", type: "text", group: "Social Media" },

      { name: "ctaSectionImage", label: "CTA Section Image", type: "file", group: "Home Page" },
      { name: "navbarPromoImage", label: "Navbar Promo Image", type: "file", group: "Navigation" },
      { name: "promoModalImage", label: "Promo Modal Image", type: "file", group: "Home Page" },
      {
        name: "homeBrandImages.primary",
        label: "Home Brand Image Primary",
        type: "file",
        group: "Home Page",
      },
      {
        name: "homeBrandImages.detail",
        label: "Home Brand Image Detail",
        type: "file",
        group: "Home Page",
      },
      {
        name: "contactMapCard.image",
        label: "Contact Map Card Image",
        type: "file",
        group: "Contact Page",
      },
      {
        name: "contactMapCard.title",
        label: "Contact Map Card Title",
        type: "text",
        group: "Contact Page",
      },
      {
        name: "contactMapCard.subtitle",
        label: "Contact Map Card Subtitle",
        type: "text",
        group: "Contact Page",
      },
      {
        name: "collectionPhilosophyImages",
        label: "Collection Philosophy Images",
        type: "file",
        multiple: true,
        group: "Collections Page",
      },
      { name: "aboutImages.hero", label: "About Images Hero", type: "file", group: "About Page" },
      {
        name: "aboutImages.ceoAvatar",
        label: "About Images CEO Avatar",
        type: "file",
        group: "About Page",
      },
      {
        name: "aboutImages.manufacturingGallery",
        label: "About Images Manufacturing Gallery",
        type: "file",
        multiple: true,
        group: "About Page",
      },
    ],
    columns: ["_id"],
  },
};

export const getEntityConfig = (entityName) => {
  return ENTITY_CONFIG[entityName] || null;
};
